import { PantryFingerprint, PantryPreset, BatchPlan, KitchenPacket } from '@/types';

export const DEFAULT_PANTRY_PRESETS: PantryPreset[] = [
  {
    id: 'preset-med',
    name: 'Mediterranean Kitchen',
    description: 'Olive oil, herbs, legumes, and grains central to Med cooking',
    ingredients: ['olive-oil', 'dried-oregano', 'dried-thyme', 'cumin', 'chickpeas', 'lentils', 'rice', 'garlic', 'onion', 'tomato-paste', 'red-wine-vinegar', 'kalamata-olives', 'capers'],
  },
  {
    id: 'preset-asian',
    name: 'Asian Pantry',
    description: 'Soy, sesame, rice vinegar, and aromatic staples',
    ingredients: ['sesame-oil', 'soy-sauce', 'rice', 'rice-vinegar', 'mirin', 'fish-sauce', 'garlic', 'ginger', 'scallions', 'chili-flakes', 'coconut-milk', 'oyster-sauce'],
  },
  {
    id: 'preset-latin',
    name: 'Latin Kitchen',
    description: 'Cumin, chili, beans, and bold aromatics',
    ingredients: ['olive-oil', 'cumin', 'chili-powder', 'smoked-paprika', 'black-beans', 'canned-tomatoes', 'rice', 'garlic', 'onion', 'cilantro', 'lime-juice', 'hot-sauce'],
  },
];

export const DEFAULT_PANTRY: PantryFingerprint = {
  id: 'pantry-default',
  userId: 'user-1',
  name: 'My Kitchen',
  activePresetId: 'preset-med',
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-01-20T14:30:00Z',
  ingredients: [
    // Oils
    { id: 'olive-oil', name: 'Olive Oil', category: 'oils', selected: true },
    { id: 'sesame-oil', name: 'Sesame Oil', category: 'oils', selected: true },
    { id: 'coconut-oil', name: 'Coconut Oil', category: 'oils', selected: false },
    { id: 'vegetable-oil', name: 'Vegetable Oil', category: 'oils', selected: true },
    { id: 'avocado-oil', name: 'Avocado Oil', category: 'oils', selected: false },
    { id: 'butter', name: 'Butter', category: 'oils', selected: true },
    // Grains
    { id: 'rice', name: 'White Rice', category: 'grains', selected: true },
    { id: 'brown-rice', name: 'Brown Rice', category: 'grains', selected: false },
    { id: 'farro', name: 'Farro', category: 'grains', selected: true },
    { id: 'quinoa', name: 'Quinoa', category: 'grains', selected: true },
    { id: 'pasta', name: 'Pasta', category: 'grains', selected: true },
    { id: 'bread-crumbs', name: 'Bread Crumbs', category: 'grains', selected: false },
    { id: 'oats', name: 'Rolled Oats', category: 'grains', selected: false },
    // Canned
    { id: 'canned-tomatoes', name: 'Canned Tomatoes', category: 'canned', selected: true },
    { id: 'chickpeas', name: 'Chickpeas', category: 'canned', selected: true },
    { id: 'black-beans', name: 'Black Beans', category: 'canned', selected: true },
    { id: 'lentils', name: 'Green Lentils', category: 'canned', selected: false },
    { id: 'coconut-milk', name: 'Coconut Milk', category: 'canned', selected: true },
    { id: 'chicken-stock', name: 'Chicken Stock', category: 'canned', selected: true },
    { id: 'tomato-paste', name: 'Tomato Paste', category: 'canned', selected: true },
    // Spices
    { id: 'cumin', name: 'Cumin', category: 'spices', selected: true },
    { id: 'smoked-paprika', name: 'Smoked Paprika', category: 'spices', selected: true },
    { id: 'chili-flakes', name: 'Chili Flakes', category: 'spices', selected: true },
    { id: 'dried-oregano', name: 'Dried Oregano', category: 'spices', selected: true },
    { id: 'dried-thyme', name: 'Dried Thyme', category: 'spices', selected: true },
    { id: 'bay-leaves', name: 'Bay Leaves', category: 'spices', selected: true },
    { id: 'black-pepper', name: 'Black Pepper', category: 'spices', selected: true },
    { id: 'cinnamon', name: 'Cinnamon', category: 'spices', selected: false },
    // Aromatics
    { id: 'garlic', name: 'Garlic', category: 'aromatics', selected: true },
    { id: 'onion', name: 'Yellow Onion', category: 'aromatics', selected: true },
    { id: 'ginger', name: 'Fresh Ginger', category: 'aromatics', selected: true },
    { id: 'scallions', name: 'Scallions', category: 'aromatics', selected: true },
    { id: 'shallots', name: 'Shallots', category: 'aromatics', selected: false },
    { id: 'cilantro', name: 'Cilantro', category: 'aromatics', selected: true },
    { id: 'parsley', name: 'Fresh Parsley', category: 'aromatics', selected: false },
    // Condiments
    { id: 'soy-sauce', name: 'Soy Sauce', category: 'condiments', selected: true },
    { id: 'fish-sauce', name: 'Fish Sauce', category: 'condiments', selected: false },
    { id: 'rice-vinegar', name: 'Rice Vinegar', category: 'condiments', selected: true },
    { id: 'red-wine-vinegar', name: 'Red Wine Vinegar', category: 'condiments', selected: true },
    { id: 'dijon-mustard', name: 'Dijon Mustard', category: 'condiments', selected: true },
    { id: 'hot-sauce', name: 'Hot Sauce', category: 'condiments', selected: true },
    { id: 'worcestershire', name: 'Worcestershire', category: 'condiments', selected: false },
    // Supporting
    { id: 'lemon', name: 'Lemons', category: 'supporting', selected: true },
    { id: 'lime-juice', name: 'Lime Juice', category: 'supporting', selected: true },
    { id: 'honey', name: 'Honey', category: 'supporting', selected: true },
    { id: 'sugar', name: 'Sugar', category: 'supporting', selected: true },
    { id: 'salt', name: 'Salt', category: 'supporting', selected: true },
    { id: 'capers', name: 'Capers', category: 'supporting', selected: false },
    { id: 'kalamata-olives', name: 'Kalamata Olives', category: 'supporting', selected: false },
  ],
};

export const MOCK_BATCH_PLAN: BatchPlan = {
  id: 'batch-001',
  title: 'Roast Chicken Week',
  coreProtein: 'Chicken',
  servingsPerRecipe: 4,
  budgetMode: 'balanced',
  usePantryFingerprint: true,
  useLeftoverChainMode: true,
  pantryFingerprintId: 'pantry-default',
  avgPantryOverlap: 72,
  avgCookTime: 38,
  createdAt: '2024-01-20T09:00:00Z',
  updatedAt: '2024-01-20T09:00:00Z',
  weeklyBudgetEstimate: {
    perServing: 8.50,
    weeklyTotal: 170,
    currency: 'USD',
  },
  leftoverLinks: [
    { sourceRecipeId: 'r1', targetRecipeId: 'r2', description: 'Roast chicken carcass & meat becomes stock and pulled chicken for rice bowls' },
    { sourceRecipeId: 'r2', targetRecipeId: 'r3', description: 'Leftover rice and chicken pieces become the base for the soup' },
    { sourceRecipeId: 'r1', targetRecipeId: 'r4', description: 'Shredded roast chicken fills the Caesar wraps' },
    { sourceRecipeId: 'r3', targetRecipeId: 'r5', description: 'Poached chicken from soup becomes grain salad protein' },
  ],
  recipes: [
    {
      id: 'r1',
      title: 'Herb Roast Chicken',
      description: 'A full roast chicken seasoned with garlic, thyme, and lemon. The backbone of the entire week — yields meat for four other meals.',
      coreProtein: 'Chicken',
      ingredients: ['whole chicken', 'garlic', 'lemon', 'dried thyme', 'dried oregano', 'olive oil', 'butter', 'onion', 'salt', 'black pepper'],
      prepTime: 15,
      cookTime: 90,
      servings: 4,
      tags: ['roast', 'classic', 'meal-prep', 'anchor'],
      leftoverRole: 'upstream',
      leftoverTargetRecipeIds: ['r2', 'r4'],
      leftoverNote: 'Reserve carcass for stock. Shred remaining meat and refrigerate.',
      chainPosition: 1,
      chainNote: 'Make this Sunday. It anchors the entire week.',
      costEstimate: { perServing: 9.50, weeklyTotal: 38, currency: 'USD' },
      pantryOverlapScore: 85,
      pantryOverlapIngredients: ['garlic', 'lemon', 'dried thyme', 'dried oregano', 'olive oil', 'butter', 'onion', 'salt', 'black pepper'],
      instructions: [
        'Preheat oven to 425°F (220°C).',
        'Pat chicken dry and place in roasting pan.',
        'Mix softened butter with minced garlic, thyme, and lemon zest. Rub under and over skin.',
        'Stuff cavity with lemon halves and onion quarters.',
        'Roast for 60–90 minutes until juices run clear (165°F internal).',
        'Rest 15 minutes before carving. Reserve carcass and pan drippings.',
      ],
      prepNotes: ['Dry-brine overnight for crispier skin', 'Save all pan drippings for the soup base'],
    },
    {
      id: 'r2',
      title: 'Chicken Rice Bowls',
      description: 'Pulled roast chicken over jasmine rice with quick-pickled cucumbers, scallions, and a sesame-ginger drizzle.',
      coreProtein: 'Chicken',
      ingredients: ['leftover chicken', 'jasmine rice', 'cucumber', 'scallions', 'sesame oil', 'soy sauce', 'rice vinegar', 'ginger', 'honey', 'sesame seeds'],
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      tags: ['bowl', 'quick', 'asian-inspired', 'leftover-chain'],
      leftoverRole: 'downstream',
      leftoverSourceRecipeId: 'r1',
      leftoverTargetRecipeIds: ['r3'],
      leftoverNote: 'Use pulled meat from the roast chicken.',
      chainPosition: 2,
      chainNote: 'Monday or Tuesday. Quick 30-min dinner.',
      costEstimate: { perServing: 5.50, weeklyTotal: 22, currency: 'USD' },
      pantryOverlapScore: 90,
      pantryOverlapIngredients: ['jasmine rice', 'sesame oil', 'soy sauce', 'rice vinegar', 'ginger', 'honey', 'scallions'],
      instructions: [
        'Cook jasmine rice per package instructions.',
        'Whisk sesame oil, soy sauce, rice vinegar, grated ginger, and honey into dressing.',
        'Thinly slice cucumbers and toss with pinch of salt and rice vinegar.',
        'Warm pulled chicken in a skillet with a splash of soy sauce.',
        'Assemble bowls: rice base, chicken, cucumbers, scallions.',
        'Drizzle sesame dressing and sprinkle sesame seeds.',
      ],
      prepNotes: ['Quick-pickle cucumbers up to 2 days ahead', 'Dressing keeps for a week refrigerated'],
    },
    {
      id: 'r3',
      title: 'Chicken & Lemon Soup',
      description: 'A bright, healing chicken soup built from your roast chicken carcass stock, with orzo, lemon, and wilted spinach.',
      coreProtein: 'Chicken',
      ingredients: ['chicken carcass', 'orzo', 'spinach', 'lemon', 'garlic', 'onion', 'carrot', 'celery', 'chicken stock', 'dried thyme', 'bay leaves', 'salt', 'black pepper'],
      prepTime: 20,
      cookTime: 45,
      servings: 6,
      tags: ['soup', 'comforting', 'batch', 'leftover-chain'],
      leftoverRole: 'downstream',
      leftoverSourceRecipeId: 'r2',
      leftoverTargetRecipeIds: ['r5'],
      leftoverNote: 'The carcass from the roast yields a rich stock.',
      chainPosition: 3,
      chainNote: 'Make midweek. Doubles as lunch and dinner.',
      costEstimate: { perServing: 4.50, weeklyTotal: 27, currency: 'USD' },
      pantryOverlapScore: 78,
      pantryOverlapIngredients: ['garlic', 'onion', 'chicken stock', 'dried thyme', 'bay leaves', 'lemon', 'salt', 'black pepper'],
      instructions: [
        'Simmer chicken carcass in water with bay leaves, onion, and celery for 1 hour. Strain stock.',
        'In a large pot, sauté diced onion, carrot, and celery in olive oil until soft.',
        'Add garlic, thyme, and pour in 8 cups of stock.',
        'Bring to boil, add orzo, cook 8 minutes.',
        'Add shredded chicken and spinach. Squeeze in lemon juice.',
        'Season generously and serve with crusty bread.',
      ],
      prepNotes: ['Make the stock the day after roasting', 'Soup improves overnight — perfect for meal prep'],
    },
    {
      id: 'r4',
      title: 'Chicken Caesar Wraps',
      description: 'Shredded roast chicken, romaine, parmesan, and a proper Caesar dressing folded into a warm flour tortilla.',
      coreProtein: 'Chicken',
      ingredients: ['leftover chicken', 'romaine lettuce', 'flour tortillas', 'parmesan', 'olive oil', 'lemon', 'dijon mustard', 'garlic', 'worcestershire', 'black pepper'],
      prepTime: 15,
      cookTime: 5,
      servings: 4,
      tags: ['wrap', 'lunch', 'quick', 'leftover-chain'],
      leftoverRole: 'downstream',
      leftoverSourceRecipeId: 'r1',
      leftoverTargetRecipeIds: [],
      leftoverNote: 'Uses shredded meat from the roast.',
      chainPosition: 4,
      chainNote: 'Great for Thursday lunch or light dinner.',
      costEstimate: { perServing: 7.00, weeklyTotal: 28, currency: 'USD' },
      pantryOverlapScore: 65,
      pantryOverlapIngredients: ['olive oil', 'lemon', 'dijon mustard', 'garlic', 'black pepper'],
      instructions: [
        'Whisk together olive oil, lemon juice, Dijon, minced garlic, and Worcestershire for dressing.',
        'Toss chopped romaine with dressing and grated parmesan.',
        'Warm tortillas in a dry skillet for 30 seconds per side.',
        'Pile salad and shredded chicken onto each tortilla.',
        'Roll tightly, slice on the diagonal, and serve.',
      ],
      prepNotes: ['Make dressing ahead and refrigerate', 'Warm chicken in dressing for maximum flavour'],
    },
    {
      id: 'r5',
      title: 'Chicken Farro Grain Salad',
      description: 'Hearty farro, pulled chicken, roasted cherry tomatoes, olives, and feta in a bright herb vinaigrette — great warm or cold.',
      coreProtein: 'Chicken',
      ingredients: ['leftover chicken', 'farro', 'cherry tomatoes', 'kalamata olives', 'feta', 'cucumber', 'red wine vinegar', 'olive oil', 'dried oregano', 'garlic', 'parsley', 'lemon'],
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      tags: ['grain-salad', 'mediterranean', 'meal-prep', 'leftover-chain'],
      leftoverRole: 'downstream',
      leftoverSourceRecipeId: 'r3',
      leftoverTargetRecipeIds: [],
      leftoverNote: 'Use poached chicken from the soup pot.',
      chainPosition: 5,
      chainNote: 'Friday finish. Zero new protein needed.',
      costEstimate: { perServing: 8.00, weeklyTotal: 32, currency: 'USD' },
      pantryOverlapScore: 80,
      pantryOverlapIngredients: ['farro', 'red wine vinegar', 'olive oil', 'dried oregano', 'garlic', 'lemon', 'kalamata olives'],
      instructions: [
        'Cook farro per package instructions. Cool slightly.',
        'Halve cherry tomatoes and roast at 400°F for 20 minutes.',
        'Whisk red wine vinegar, olive oil, garlic, and oregano into vinaigrette.',
        'Combine farro, tomatoes, olives, and diced cucumber.',
        'Add pulled chicken and drizzle vinaigrette generously.',
        'Top with crumbled feta and chopped parsley.',
      ],
      prepNotes: ['Farro can be cooked 3 days ahead', 'Salad holds well — flavours improve over time'],
    },
  ],
};

export const MOCK_KITCHEN_PACKET: KitchenPacket = {
  id: 'packet-001',
  batchId: 'batch-001',
  title: 'Roast Chicken Week — Kitchen Packet',
  generatedAt: '2024-01-20T09:30:00Z',
  summary: {
    recipeCount: 5,
    avgCookTime: 38,
    pantryOverlapPct: 72,
    weeklyCost: { perServing: 8.50, weeklyTotal: 147, currency: 'USD' },
    chainRelationships: 4,
  },
  groceryList: [
    { ingredient: 'Whole Chicken (4–5 lb)', quantity: '1', recipeIds: ['r1'], isPantryStaple: false },
    { ingredient: 'Jasmine Rice', quantity: '2 cups', recipeIds: ['r2'], isPantryStaple: true },
    { ingredient: 'Orzo Pasta', quantity: '1½ cups', recipeIds: ['r3'], isPantryStaple: false },
    { ingredient: 'Flour Tortillas', quantity: '8', recipeIds: ['r4'], isPantryStaple: false },
    { ingredient: 'Farro', quantity: '1½ cups', recipeIds: ['r5'], isPantryStaple: true },
    { ingredient: 'Romaine Lettuce', quantity: '1 head', recipeIds: ['r4'], isPantryStaple: false },
    { ingredient: 'Cherry Tomatoes', quantity: '2 pints', recipeIds: ['r5'], isPantryStaple: false },
    { ingredient: 'Baby Spinach', quantity: '5 oz bag', recipeIds: ['r3'], isPantryStaple: false },
    { ingredient: 'Cucumber', quantity: '2 medium', recipeIds: ['r2', 'r5'], isPantryStaple: false },
    { ingredient: 'Feta Cheese', quantity: '4 oz', recipeIds: ['r5'], isPantryStaple: false },
    { ingredient: 'Parmesan (block)', quantity: '2 oz', recipeIds: ['r4'], isPantryStaple: false },
    { ingredient: 'Carrot', quantity: '3 medium', recipeIds: ['r3'], isPantryStaple: false },
    { ingredient: 'Celery', quantity: '4 stalks', recipeIds: ['r3'], isPantryStaple: false },
    { ingredient: 'Lemons', quantity: '4', recipeIds: ['r1', 'r3', 'r4', 'r5'], isPantryStaple: true },
  ],
  prepPlan: [
    {
      recipeId: 'r1',
      recipeTitle: 'Herb Roast Chicken',
      suggestedDay: 0,
      notes: ['Dry-brine chicken overnight Saturday', 'Roast Sunday afternoon', 'Carve and shred; store separately', 'Make stock from carcass Sunday evening'],
    },
    {
      recipeId: 'r2',
      recipeTitle: 'Chicken Rice Bowls',
      suggestedDay: 1,
      notes: ['Quick-pickle cucumbers in morning', 'Cook rice and assemble bowls in 30 min'],
    },
    {
      recipeId: 'r3',
      recipeTitle: 'Chicken & Lemon Soup',
      suggestedDay: 3,
      notes: ['Use pre-made stock', 'Soup improves overnight — make Wednesday, eat Thursday'],
    },
    {
      recipeId: 'r4',
      recipeTitle: 'Chicken Caesar Wraps',
      suggestedDay: 4,
      notes: ['Make Caesar dressing ahead', 'Assemble just before serving to avoid soggy tortillas'],
    },
    {
      recipeId: 'r5',
      recipeTitle: 'Chicken Farro Grain Salad',
      suggestedDay: 5,
      notes: ['Cook farro early in the week', 'Roast tomatoes Friday morning', 'Assemble for Friday dinner'],
    },
  ],
  leftoverMap: [
    { sourceRecipeId: 'r1', targetRecipeId: 'r2', description: 'Shredded roast chicken → Rice Bowls' },
    { sourceRecipeId: 'r1', targetRecipeId: 'r4', description: 'Shredded roast chicken → Caesar Wraps' },
    { sourceRecipeId: 'r2', targetRecipeId: 'r3', description: 'Leftover rice + chicken → Soup base' },
    { sourceRecipeId: 'r3', targetRecipeId: 'r5', description: 'Poached chicken from soup → Grain Salad' },
  ],
  cookOrder: [
    { day: 0, recipeId: 'r1', recipeTitle: 'Herb Roast Chicken' },
    { day: 1, recipeId: 'r2', recipeTitle: 'Chicken Rice Bowls' },
    { day: 3, recipeId: 'r3', recipeTitle: 'Chicken & Lemon Soup' },
    { day: 4, recipeId: 'r4', recipeTitle: 'Chicken Caesar Wraps' },
    { day: 5, recipeId: 'r5', recipeTitle: 'Chicken Farro Grain Salad' },
  ],
  sections: {
    groceryList: true,
    prepNotes: true,
    leftoverMap: true,
    cookOrder: true,
    recipeZines: false,
  },
};
