import {
  Batch,
  BatchInputs,
  CoreProtein,
  PantryIngredient,
  RecipeConcept,
  Recipe,
  ThemeConfig,
} from '@/types';

export const CORE_PROTEINS: { value: CoreProtein; label: string; description: string }[] = [
  { value: 'chicken-thighs', label: 'Chicken Thighs', description: 'Rich, forgiving, and versatile' },
  { value: 'ground-beef', label: 'Ground Beef', description: 'Bold, hearty, and adaptable' },
  { value: 'sirloin-steak', label: 'Sirloin Steak', description: 'Elegant, quick-cooking, premium' },
];

export const PANTRY_INGREDIENTS: { value: PantryIngredient; label: string; group: string }[] = [
  { value: 'onions', label: 'Onions', group: 'Aromatics' },
  { value: 'garlic', label: 'Garlic', group: 'Aromatics' },
  { value: 'ginger', label: 'Ginger', group: 'Aromatics' },
  { value: 'potatoes', label: 'Potatoes', group: 'Starches' },
  { value: 'rice', label: 'Rice', group: 'Starches' },
  { value: 'lentils', label: 'Lentils', group: 'Legumes' },
  { value: 'beans', label: 'Beans', group: 'Legumes' },
  { value: 'canned-tomatoes', label: 'Canned Tomatoes', group: 'Pantry' },
  { value: 'herbs', label: 'Fresh Herbs', group: 'Flavour' },
  { value: 'citrus', label: 'Citrus', group: 'Flavour' },
  { value: 'turmeric', label: 'Turmeric', group: 'Spices' },
  { value: 'yogurt', label: 'Yogurt', group: 'Dairy' },
  { value: 'greens', label: 'Leafy Greens', group: 'Vegetables' },
];

export const THEMES: ThemeConfig[] = [
  {
    id: 'arcane-editorial',
    name: 'Arcane Editorial',
    description: 'Deep pine greens and cream parchment with brass accents. Bold serif headings.',
    colors: {
      background: '#fefdf8',
      surface: '#ffffff',
      text: '#103629',
      accent: '#b08d3f',
      muted: '#747638',
    },
    typography: { headingFont: 'Playfair Display', bodyFont: 'Inter' },
    cardDensity: 'comfortable',
    noteStyle: 'bordered',
    imageFraming: 'full-bleed',
  },
  {
    id: 'ayurvedic-kitchen',
    name: 'Ayurvedic Kitchen',
    description: 'Warm turmeric tones with terracotta accents. Gentle and nurturing layout.',
    colors: {
      background: '#fffbf0',
      surface: '#fff8e7',
      text: '#3d2b1f',
      accent: '#c4a35a',
      muted: '#8b7355',
    },
    typography: { headingFont: 'Playfair Display', bodyFont: 'Inter' },
    cardDensity: 'spacious',
    noteStyle: 'highlighted',
    imageFraming: 'inset',
  },
  {
    id: 'rustic-pantry',
    name: 'Rustic Pantry',
    description: 'Earthy olive and stone tones. Dense, practical layout for everyday cooking.',
    colors: {
      background: '#f5f3ef',
      surface: '#edeae4',
      text: '#2c2a25',
      accent: '#5e602c',
      muted: '#8b8d4a',
    },
    typography: { headingFont: 'Inter', bodyFont: 'Inter' },
    cardDensity: 'compact',
    noteStyle: 'inset',
    imageFraming: 'inset',
  },
  {
    id: 'meal-prep-clean',
    name: 'Meal Prep Clean',
    description: 'Clinical white and grey with pine green pops. Optimised for print and scanning.',
    colors: {
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#1a1a2e',
      accent: '#1e5c47',
      muted: '#64748b',
    },
    typography: { headingFont: 'Inter', bodyFont: 'Inter' },
    cardDensity: 'compact',
    noteStyle: 'bordered',
    imageFraming: 'circular',
  },
];

const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'recipe-1',
    conceptId: 'concept-1',
    batchId: 'batch-1',
    title: 'Roasted Thighs with Lemon & Herbs',
    subtitle: 'Golden tray-baked thighs with roasted potatoes and a bright herb finish',
    coreProtein: 'chicken-thighs',
    servings: 4,
    cookTime: 45,
    prepTime: 15,
    styleTag: 'Rustic European',
    cuisineInspiration: 'French Bistro',
    format: 'roast-tray-bake',
    ingredients: [
      { name: 'Chicken thighs', amount: '8', unit: 'pieces', note: 'bone-in, skin-on' },
      { name: 'Potatoes', amount: '600', unit: 'g', note: 'halved' },
      { name: 'Garlic', amount: '8', unit: 'cloves', note: 'unpeeled' },
      { name: 'Lemon', amount: '2', unit: 'whole', note: 'quartered' },
      { name: 'Fresh thyme', amount: '6', unit: 'sprigs' },
      { name: 'Fresh rosemary', amount: '3', unit: 'sprigs' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp' },
      { name: 'Sea salt', amount: '1.5', unit: 'tsp' },
      { name: 'Black pepper', amount: '1', unit: 'tsp' },
    ],
    steps: [
      { number: 1, instruction: 'Preheat oven to 220°C/425°F. Pat the chicken dry and season generously.', duration: 5 },
      { number: 2, instruction: 'Toss potatoes and garlic with olive oil, salt, and pepper on a large roasting tray.', duration: 5 },
      { number: 3, instruction: 'Nestle the chicken thighs skin-side up among the potatoes. Scatter lemon quarters and herbs.', duration: 3 },
      { number: 4, instruction: 'Roast for 45 minutes until skin is deeply golden and potatoes are tender.', duration: 45, tip: 'Rotate the tray halfway through for even browning.' },
      { number: 5, instruction: 'Rest for 5 minutes before serving. Squeeze the roasted lemon over everything.', duration: 5 },
    ],
    chefNote: 'The key is really dry chicken skin — pat it thoroughly with kitchen paper. The roasted garlic cloves become spreadable and sweet.',
    wellnessNote: 'Bone-in thighs provide collagen and gelatin for gut support. Lemon aids iron absorption from the herbs.',
    leftoverNote: 'Shred leftover meat and toss with the potatoes for a next-day hash, or stuff into wraps with yogurt sauce.',
    balanceTags: ['Warming', 'Grounding'],
    overlapScore: 87,
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },
  {
    id: 'recipe-2',
    conceptId: 'concept-2',
    batchId: 'batch-1',
    title: 'Turmeric Chicken Bowl',
    subtitle: 'Golden-spiced thighs over jasmine rice with ginger yogurt',
    coreProtein: 'chicken-thighs',
    servings: 4,
    cookTime: 35,
    prepTime: 20,
    styleTag: 'Ayurvedic Inspired',
    cuisineInspiration: 'South Asian',
    format: 'bowl-rice',
    ingredients: [
      { name: 'Chicken thighs', amount: '600', unit: 'g', note: 'boneless, diced' },
      { name: 'Jasmine rice', amount: '300', unit: 'g' },
      { name: 'Turmeric', amount: '1.5', unit: 'tsp' },
      { name: 'Ginger', amount: '3', unit: 'cm', note: 'grated' },
      { name: 'Garlic', amount: '4', unit: 'cloves', note: 'minced' },
      { name: 'Onion', amount: '1', unit: 'large', note: 'sliced' },
      { name: 'Full-fat yogurt', amount: '200', unit: 'ml' },
      { name: 'Coriander', amount: '1', unit: 'bunch' },
      { name: 'Coconut oil', amount: '2', unit: 'tbsp' },
      { name: 'Cumin seeds', amount: '1', unit: 'tsp' },
    ],
    steps: [
      { number: 1, instruction: 'Rinse and cook rice according to packet. Keep warm.', duration: 20 },
      { number: 2, instruction: 'Marinate chicken with turmeric, half the ginger, half the garlic, salt, and oil for 10 minutes.', duration: 10 },
      { number: 3, instruction: 'In a skillet over high heat, sear chicken pieces until golden and cooked through, about 12 minutes.', duration: 12 },
      { number: 4, instruction: 'In the same pan, fry onion with cumin seeds until caramelised. Add remaining garlic and ginger.', duration: 8, tip: 'Low and slow for the onions creates sweetness.' },
      { number: 5, instruction: 'Serve rice topped with chicken, onions, a generous dollop of yogurt, and fresh coriander.', duration: 3 },
    ],
    chefNote: 'Don\'t rush the onion caramelisation — that deep sweetness is what makes the bowl sing.',
    wellnessNote: 'Turmeric\'s curcumin has anti-inflammatory properties. The fat from coconut oil enhances absorption. Ginger supports digestion.',
    leftoverNote: 'Pack rice and chicken separately for meal prep lunches. Reheat rice with a splash of water.',
    balanceTags: ['Warming', 'Balanced'],
    overlapScore: 82,
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },
];

const SAMPLE_CONCEPTS: RecipeConcept[] = [
  {
    id: 'concept-1',
    batchId: 'batch-1',
    recipeId: 'recipe-1',
    title: 'Roasted Thighs with Lemon & Herbs',
    subtitle: 'Golden tray-baked thighs with roasted potatoes and herb finish',
    format: 'roast-tray-bake',
    styleTag: 'Rustic European',
    cuisineInspiration: 'French Bistro',
    estimatedCookTime: 60,
    balanceTags: ['Warming', 'Grounding'],
    overlapScore: 87,
    status: 'approved',
  },
  {
    id: 'concept-2',
    batchId: 'batch-1',
    recipeId: 'recipe-2',
    title: 'Turmeric Chicken Bowl',
    subtitle: 'Golden-spiced thighs over jasmine rice with ginger yogurt',
    format: 'bowl-rice',
    styleTag: 'Ayurvedic Inspired',
    cuisineInspiration: 'South Asian',
    estimatedCookTime: 55,
    balanceTags: ['Warming', 'Balanced'],
    overlapScore: 82,
    status: 'approved',
  },
  {
    id: 'concept-3',
    batchId: 'batch-1',
    title: 'Chicken & Bean Skillet',
    subtitle: 'Quick weeknight skillet with white beans and wilted greens',
    format: 'skillet',
    styleTag: 'Mediterranean',
    cuisineInspiration: 'Italian Countryside',
    estimatedCookTime: 30,
    balanceTags: ['Grounding', 'Balanced'],
    overlapScore: 79,
    status: 'pending',
  },
  {
    id: 'concept-4',
    batchId: 'batch-1',
    title: 'Chicken & Lentil Stew',
    subtitle: 'Warming red lentil stew with canned tomatoes and citrus gremolata',
    format: 'comfort',
    styleTag: 'North African',
    cuisineInspiration: 'Moroccan',
    estimatedCookTime: 50,
    balanceTags: ['Warming', 'Grounding'],
    overlapScore: 91,
    status: 'pending',
  },
  {
    id: 'concept-5',
    batchId: 'batch-1',
    title: 'Shredded Chicken Leftover Wraps',
    subtitle: 'Light lunch wraps using batch-cooked chicken with herb yogurt',
    format: 'lighter-leftover',
    styleTag: 'Fresh & Light',
    cuisineInspiration: 'Eastern Mediterranean',
    estimatedCookTime: 15,
    balanceTags: ['Cooling', 'Balanced'],
    overlapScore: 76,
    status: 'pending',
  },
  {
    id: 'concept-6',
    batchId: 'batch-1',
    title: 'Spiced Chicken Rice Pilaf',
    subtitle: 'One-pot pilaf with caramelised onions, raisins, and warming spices',
    format: 'bowl-rice',
    styleTag: 'Levantine',
    cuisineInspiration: 'Persian',
    estimatedCookTime: 55,
    balanceTags: ['Warming', 'Grounding'],
    overlapScore: 84,
    status: 'swapped',
  },
  {
    id: 'concept-7',
    batchId: 'batch-2',
    title: 'Korean-Style Ground Beef Bowl',
    subtitle: 'Sesame-glazed beef over rice with pickled cucumber and chilli',
    format: 'bowl-rice',
    styleTag: 'Korean Inspired',
    cuisineInspiration: 'Korean',
    estimatedCookTime: 25,
    balanceTags: ['Warming', 'Balanced'],
    overlapScore: 88,
    status: 'approved',
  },
  {
    id: 'concept-8',
    batchId: 'batch-2',
    title: 'Beef & Tomato Skillet',
    subtitle: 'Rich tomato-braised beef with herbs and creamy polenta',
    format: 'skillet',
    styleTag: 'Italian Rustic',
    cuisineInspiration: 'Italian',
    estimatedCookTime: 40,
    balanceTags: ['Warming', 'Grounding'],
    overlapScore: 85,
    status: 'pending',
  },
];

export const SAMPLE_BATCHES: Batch[] = [
  {
    id: 'batch-1',
    inputs: {
      name: 'Autumn Chicken Week',
      coreProtein: 'chicken-thighs',
      batchSize: 5,
      pantryIngredients: ['onions', 'garlic', 'potatoes', 'rice', 'lentils', 'canned-tomatoes', 'herbs', 'citrus', 'ginger', 'turmeric', 'yogurt'],
      pantryRuleMode: 'Standard',
      seasonalMode: 'Autumn',
      balanceProfile: 'Warming',
      exclusions: ['nuts', 'shellfish'],
      maxCookTime: 60,
      preferredStyle: 'Rustic European',
    },
    concepts: SAMPLE_CONCEPTS.filter(c => c.batchId === 'batch-1'),
    recipes: SAMPLE_RECIPES.filter(r => r.batchId === 'batch-1'),
    status: 'reviewing',
    activeTheme: 'arcane-editorial',
    createdAt: '2024-11-01T09:00:00Z',
    updatedAt: '2024-11-01T11:30:00Z',
  },
  {
    id: 'batch-2',
    inputs: {
      name: 'Winter Beef Batch',
      coreProtein: 'ground-beef',
      batchSize: 4,
      pantryIngredients: ['onions', 'garlic', 'canned-tomatoes', 'beans', 'greens', 'herbs'],
      pantryRuleMode: 'Flexible',
      seasonalMode: 'Winter',
      balanceProfile: 'Grounding',
      exclusions: [],
      maxCookTime: 45,
      preferredStyle: 'Hearty',
    },
    concepts: SAMPLE_CONCEPTS.filter(c => c.batchId === 'batch-2'),
    recipes: [],
    status: 'draft',
    activeTheme: 'rustic-pantry',
    createdAt: '2024-11-05T14:00:00Z',
    updatedAt: '2024-11-05T14:00:00Z',
  },
];

export function generateMockBatch(inputs: BatchInputs): Batch {
  const id = `batch-${Date.now()}`;
  const concepts: RecipeConcept[] = [
    {
      id: `${id}-c1`,
      batchId: id,
      title: `Roasted ${inputs.coreProtein.replace(/-/g, ' ')} Tray Bake`,
      subtitle: 'Simple tray-baked with seasonal vegetables',
      format: 'roast-tray-bake',
      styleTag: inputs.preferredStyle || 'Rustic',
      cuisineInspiration: 'European',
      estimatedCookTime: Math.min(inputs.maxCookTime, 55),
      balanceTags: [inputs.balanceProfile, 'Grounding'],
      overlapScore: 85,
      status: 'pending',
    },
    {
      id: `${id}-c2`,
      batchId: id,
      title: `${inputs.balanceProfile} Bowl`,
      subtitle: 'Nourishing bowl with pantry staples',
      format: 'bowl-rice',
      styleTag: 'Contemporary',
      cuisineInspiration: 'Pan-Asian',
      estimatedCookTime: Math.min(inputs.maxCookTime, 40),
      balanceTags: [inputs.balanceProfile],
      overlapScore: 78,
      status: 'pending',
    },
  ];

  return {
    id,
    inputs,
    concepts,
    recipes: [],
    status: 'draft',
    activeTheme: 'arcane-editorial',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
